name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e79203ab711febe944deff62ee9bbe4b07a0cf2a0f7a08e1504d5412e8381f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
