name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9c81a536f479a68c1e8145886cbb556a018a452fd969b27355aadb43ce60e4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
