name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d81227f198ad6ff15979b86cdabd77f16572898850cea489a4d98331e1959333"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
