name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bea23ba19c9b88ffa436ee92ae3660ef8a7758347ace47dacfa51992a9071f5b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
