name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd633fccd47fe9deaf1746a4cc19311eb338010dd737bfe018bdc21176afebc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
