name = "Knight Quest"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9971a6550db68213e47331807f34eb3ed9a2679e06e349a503f6dd48dd248717"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
