name = "21 Core v2"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0ffaac919e080dc2124f0c7b788d2b3548ed62fc41ba9a59ebf03390f86225f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
