name = "21 Core v2"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "062146b5b01153fb8d069357e31e7d2b2949cd3b821c5e8cce1cc1741436493e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
