name = "21 Core v2"
author = "robonebi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90d80cd738576be72c5fec7bb7d7ff783f10e12c1bbaa7a0885182da71562bab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
