name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96e080d74b49408025fc0585b555492c7ec4aaf61c9b643cc3f1c2eabca106b4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
