name = "Cobblemon: Ho-Oh's Chosen"
author = "robonebi"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa896e09c96aac07fc4d3d6bb5b3b5ba3a203bf7f65cd207fe96f4d1ab694dfb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "global_packs/required_data"
